#!/usr/bin/env bash
# Start-of-run hygiene + source roll for the /decompile skill.
#
# Run from inside a project (or agent) worktree. Restores tracked files that
# the build can stomp, warns on known parallel-agent merge artifacts, checks
# branch staleness vs origin/main, and prints a randomly-rolled candidate
# source number for the /decompile skill to commit to.
#
# Output (last line) is `source=N` where N is 1..5.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# 1. Restore tracked report.json if dirty.
#    Background: report.json is regenerated by the land script; local builds
#    stomp it and a dirty tree blocks landing. See feedback_report_json_tracked.md.
if [[ -f report.json ]] && ! git diff --quiet -- report.json 2>/dev/null; then
    echo "(preflight) restoring tracked report.json"
    git checkout HEAD -- report.json
fi

# 2. Warn on stacked NON_MATCHING wraps from parallel agent merges.
#    Pattern: two `#ifdef NON_MATCHING` lines with no `#` directive between
#    them = nested wrap. Sequential wraps in the same file have `#endif` /
#    `#else` between, so they contain `#` and are filtered out.
#    See feedback_parallel_agent_wrap_nesting.md.
if [[ -d src ]]; then
    STACKED=$(find src -name '*.c' -print0 \
              | xargs -0 grep -lzP '#ifdef NON_MATCHING[^#]*#ifdef NON_MATCHING' 2>/dev/null \
              || true)
    if [[ -n "$STACKED" ]]; then
        echo "(preflight) WARNING: stacked NON_MATCHING wraps in:"
        printf '  %s\n' $STACKED
    fi
fi

# 3. Warn if branch is behind origin/main.
if [[ "$BRANCH" != "main" ]]; then
    if git ls-remote --exit-code --heads origin main >/dev/null 2>&1; then
        git fetch -q origin main 2>/dev/null || true
        BEHIND=$(git rev-list --count "HEAD..origin/main" 2>/dev/null || echo 0)
        if [[ "${BEHIND:-0}" -gt 0 ]]; then
            echo "(preflight) branch $BRANCH is $BEHIND commit(s) behind origin/main; consider 'git rebase origin/main'"
        fi
    fi
fi

# 4. Warn on memory-dir bloat. The convention (CLAUDE.md, 2026-05-05) is that
#    project knowledge belongs in docs/ not in feedback memos. Fresh
#    feedback_*.md files that aren't tombstones signal the convention is
#    drifting — surface it before the dir balloons again.
MEM_DIR="$HOME/.claude/projects/-home-dan-Documents-code-decomp/memory"
if [[ -d "$MEM_DIR" ]]; then
    FEEDBACK_NEW=$(grep -L '^type: pointer$' "$MEM_DIR"/feedback_*.md 2>/dev/null | wc -l)
    if [[ "${FEEDBACK_NEW:-0}" -gt 10 ]]; then
        echo "(preflight) NOTE: $FEEDBACK_NEW feedback memos in $MEM_DIR are not tombstones."
        echo "(preflight)       Project-knowledge memos belong in docs/ — see CLAUDE.md."
        echo "(preflight)       Review them, append to relevant docs/*.md, then tombstone."
    fi
fi

# 5. Roll a candidate source for /decompile (1..5). The skill commits to whatever
#    candidate this source yields — see /decompile "Picking a function".
echo "source=$((RANDOM % 5 + 1))"
